# Generated by Django 5.2.7 on 2025-10-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
