# Generated by Django 5.2.7 on 2025-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_employee_delete_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('employees_count', models.IntegerField(default=1, verbose_name='Employees Count')),
                ('location', models.CharField(choices=[('SF', 'Sofia'), ('PL', 'Plovdiv'), ('VR', 'Varna'), ('BS', 'Burgas')], max_length=20)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
