# Generated by Django 5.0.4 on 2025-12-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
