# Generated by Django 5.0.4 on 2025-11-10 06:59

from django.db import migrations

def create_unique_brands(apps, schema_editor):

    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrands = apps.get_model('main_app', 'UniqueBrands')

    shoes = ShoeModel.objects.values_list('brand', flat=True).distinct()
    name_brads = [UniqueBrands(brand_name=brand_name) for brand_name in shoes]

    UniqueBrands.objects.bulk_create(name_brads)

def delete_unique_brands(apps, schema_editor):
    UniqueBrands = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, reverse_code=delete_unique_brands),
    ]
