# Generated by Django 5.2.7 on 2025-11-13 10:25

from django.db import migrations


def set_age_group(apps, scheme_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    people = PersonModel.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = 'Child'
        elif person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'
        person.save()

def set_age(apps, scheme_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    default_age = PersonModel._meta.get_field('age_group').default

    for person in PersonModel.objects.all():
        person.age_group = default_age
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(code=set_age_group, reverse_code=set_age),
    ]
