# Generated by Django 5.2.7 on 2025-11-13 10:39

from django.db import migrations

def item_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    items = ItemModel.objects.all()

    for item in items:

        if item.price <= 10:
            item.rarity = 'Rare'

        elif item.price <= 20:
            item.rarity = 'Very Rare'

        elif item.price <= 30:
            item.rarity = 'Extremely Rare'

        else:
            item.rarity = 'Mega Rare'

        item.save()

def delete_item(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    default_age = ItemModel._meta.get_field('rarity').default

    for item in ItemModel.objects.all():
        item.rarity = default_age
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(code=item_rarity, reverse_code=delete_item),
    ]
