# Generated by Django 5.2.7 on 2025-11-13 10:41

from django.db import migrations

SMART_MULTIPLE = 120
MAX_PRICE = 750

def set_new_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    smart = list(SmartphoneModel.objects.all())

    for phone in smart:
        phone.price = len(phone.brand) * SMART_MULTIPLE

    SmartphoneModel.objects.bulk_update(smart, ['price'])


def set_new_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    smart = list(SmartphoneModel.objects.all())

    for phone in smart:
        phone.category = 'Expensive' if phone.price >= MAX_PRICE else 'Cheap'

    SmartphoneModel.objects.bulk_update(smart, ['category'])


def price_default(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_price = SmartphoneModel._meta.get_field('price').default
    smart = list(SmartphoneModel.objects.all())

    for phone in smart:
        phone.price = default_price

    SmartphoneModel.objects.bulk_update(smart, ['price'])


def category_default(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_category = SmartphoneModel._meta.get_field('category').default
    smart = list(SmartphoneModel.objects.all())

    for phone in smart:
        phone.category = default_category

    SmartphoneModel.objects.bulk_update(smart, ['category'])


def set_price_category(apps, schema_editor):
    set_new_price(apps, schema_editor)
    set_new_category(apps, schema_editor)

def default_price_category(apps, schema_editor):
    price_default(apps, schema_editor)
    category_default(apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(code=set_price_category, reverse_code=default_price_category),
    ]
