# Generated by Django 5.2.7 on 2025-11-15 06:03
from datetime import timedelta

from django.db import migrations

def set_orders(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')
    orders = OrderModel.objects.all()

    for order in orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
            order.save()

        elif order.status == 'Completed':
            order.warranty = "24 months"
            order.save()

        elif order.status == 'Cancelled':
            order.delete()
            continue

        order.save()


def revers_order(apps, schema_editor):
    OrdeMetod = apps.get_model('main_app', 'Order')
    default_order = OrdeMetod._meta.get_field('warranty').default
    orders = OrdeMetod.objects.all()

    for order in orders:
        order.warranty = default_order
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(code=set_orders, reverse_code=revers_order),

    ]
