# Generated by Django 5.0.4 on 2025-11-05 18:17

import random
from django.db import migrations

def all_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    products = Product.objects.all()
    barcodes = random.sample(range(100_000_000, 999_999_999 + 1), len(products))
    for product in range(len(products)):
        p = products[product]
        p.barcode = barcodes[product]
        p.save()

def remove_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    for product in Product.objects.all():
        product.barcode = 0
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_barcode'),
    ]

    operations = [
        migrations.RunPython(all_barcode, reverse_code=remove_barcode),
    ]

